#include <stdio.h>
#include <string.h>

char commency[] = "EATROSHNIDCLUGMFPWBYVKXJQZ";//"ETAOINSHRDLCUMWFGYPBVKJXQZ";
char save[] = "QVJDBMEDGBQJJSGWQGZSNSZBNWUXBNJDSYSNCBWUMNICISTBUJACBENQYDSNUQENSSJDQJUDQFSUYSQNSKQUSWMZQJSWQJJDSFCGEUGSKUZDBBVCGUJNQJXBNWQXNSSUZDBBVZDQNJSNSWCGQABMJQHMQNJSNBXQTCVSXNBTDCUDBTSENQTTQNUZDBBVUIQNCSWCGHMQVCJLWMNCGEJDSSVCPQASJDQGSNQAMJJDSZMNNCZMVMTKQUWCZJQJSWALVQKJDNBMEDBMJSGEVQGWQGWJDSUZDBBVKBMVWDQISYNBICWSWQGCGJSGUCISSWMZQJCBGCGVQJCGENQTTQNQGWJDSZVQUUCZUQJJDSQESBXUDQFSUYSQNSTQNNCSWJDSLSQNBVWQGGSDQJDQKQLJDSZBGUCUJBNLZBMNJBXJDSWCBZSUSBXKBNZSUJSNCUUMSWQTQNNCQESVCZSGZSBGGBISTASNJKBBXDQJDQKQLUGSCEDABMNUYBUJSWABGWUJDSGSOJWQLQUUMNSJLJDQJJDSNSKSNSGBCTYSWCTSGJUJBJDSTQNNCQESJDSZBMYVSTQLDQISQNNQGESWJDSZSNSTBGLCGUBTSDQUJSUCGZSJDSKBNZSUJSNZDQGZSVVBNQVVBKSWJDSTQNNCQESAQGGUJBASNSQWBGZSCGUJSQWBXJDSMUMQVJDNSSJCTSUQGGSUYNSEGQGZLZBMVWDQISASSGJDSNSQUBGXBNJDCUUCOTBGJDUQXJSNJDSTQNNCQESUDSEQISACNJDJBQWQMEDJSNUMUQGGQKDBKQUAQYJCUSWBGTQLJKCGUUBGDQTGSJQGWWQMEDJSNRMWCJDXBVVBKSWQVTBUJJKBLSQNUVQJSNQGWKSNSAQYJCUSWBGXSANMQNLDQTGSJWCSWBXMGFGBKGZQMUSUQJJDSQESBXQGWKQUAMNCSWBGQMEMUJQXJSNJDSACNJDBXJDSJKCGUJDSNSQNSXSKDCUJBNCZQVJNQZSUBXUDQFSUYSQNSMGJCVDSCUTSGJCBGSWQUYQNJBXJDSVBGWBGJDSQJNSUZSGSCGASZQMUSBXJDCUEQYUZDBVQNUNSXSNJBJDSLSQNUASJKSSGQGWQUUDQFSUYSQNSUVBUJLSQNUACBENQYDSNUQJJSTYJCGEJBQZZBMGJXBNJDCUYSNCBWDQISNSYBNJSWTQGLQYBZNLYDQVUJBNCSUGCZDBVQUNBKSUDQFSUYSQNSUXCNUJACBENQYDSNNSZBMGJSWQUJNQJXBNWVSESGWJDQJUDQFSUYSQNSXVSWJDSJBKGXBNVBGWBGJBSUZQYSYNBUSZMJCBGXBNWSSNYBQZDCGEQGBJDSNSCEDJSSGJDZSGJMNLUJBNLDQUUDQFSUYSQNSUJQNJCGEDCUJDSQJNCZQVZQNSSNTCGWCGEJDSDBNUSUBXJDSQJNSYQJNBGUCGVBGWBGRBDGQMANSLNSYBNJSWJDQJUDQFSUYSQNSDQWASSGQZBMGJNLUZDBBVTQUJSNUBTSJKSGJCSJDZSGJMNLUZDBVQNUDQISUMEESUJSWJDQJUDQFSUYSQNSTQLDQISASSGSTYVBLSWQUQUZDBBVTQUJSNALQVSOQGWSNDBEDJBGBXVQGZQUDCNSQZQJDBVCZVQGWBKGSNKDBGQTSWQZSNJQCGKCVVCQTUDQFSUDQXJSCGDCUKCVVGBSICWSGZSUMAUJQGJCQJSUUMZDUJBNCSUBJDSNJDQGDSQNUQLZBVVSZJSWQXJSNDCUWSQJDQVJDBMEDGBQJJSGWQGZSNSZBNWUXBNJDSYSNCBWUMNICISTBUJACBENQYDSNUQENSSJDQJUDQFSUYSQNSKQUSWMZQJSWQJJDSFCGEUGSKUZDBBVCGUJNQJXBNWQXNSSUZDBBVZDQNJSNSWCGQABMJQHMQNJSNBXQTCVSXNBTDCUDBTSENQTTQNUZDBBVUIQNCSWCGHMQVCJLWMNCGEJDSSVCPQASJDQGSNQAMJJDSZMNNCZMVMTKQUWCZJQJSWALVQKJDNBMEDBMJSGEVQGWQGWJDSUZDBBVKBMVWDQISYNBICWSWQGCGJSGUCISSWMZQJCBGCGVQJCGENQTTQNQGWJDSZVQUUCZUQJJDSQESBXUDQFSUYSQNSTQNNCSWJDSLSQNBVWQGGSDQJDQKQLJDSZBGUCUJBNLZBMNJBXJDSWCBZSUSBXKBNZSUJSNCUUMSWQTQNNCQESVCZSGZSBGGBISTASNJKBBXDQJDQKQLUGSCEDABMNUYBUJSWABGWUJDSGSOJWQLQUUMNSJLJDQJJDSNSKSNSGBCTYSWCTSGJUJBJDSTQNNCQESJDSZBMYVSTQLDQISQNNQGESWJDSZSNSTBGLCGUBTSDQUJSUCGZSJDSKBNZSUJSNZDQGZSVVBNQVVBKSWJDSTQNNCQESAQGGUJBASNSQWBGZSCGUJSQWBXJDSMUMQVJDNSSJCTSUQGGSUYNSEGQGZLZBMVWDQISASSGJDSNSQUBGXBNJDCUUCOTBGJDUQXJSNJDSTQNNCQESUDSEQISACNJDJBQWQMEDJSNUMUQGGQKDBKQUAQYJCUSWBGTQLJKCGUUBGDQTGSJQGWWQMEDJSNRMWCJDXBVVBKSWQVTBUJJKBLSQNUVQJSNQGWKSNSAQYJCUSWBGXSANMQNLDQTGSJWCSWBXMGFGBKGZQMUSUQJJDSQESBXQGWKQUAMNCSWBGQMEMUJQXJSNJDSACNJDBXJDSJKCGUJDSNSQNSXSKDCUJBNCZQVJNQZSUBXUDQFSUYSQNSMGJCVDSCUTSGJCBGSWQUYQNJBXJDSVBGWBGJDSQJNSUZSGSCGASZQMUSBXJDCUEQYUZDBVQNUNSXSNJBJDSLSQNUASJKSSGQGWQUUDQFSUYSQNSUVBUJLSQNUACBENQYDSNUQJJSTYJCGEJBQZZBMGJXBNJDCUYSNCBWDQISNSYBNJSWTQGLQYBZNLYDQVUJBNCSUGCZDBVQUNBKSUDQFSUYSQNSUXCNUJACBENQYDSNNSZBMGJSWQUJNQJXBNWVSESGWJDQJUDQFSUYSQNSXVSWJDSJBKGXBNVBGWBGJBSUZQYSYNBUSZMJCBGXBNWSSNYBQZDCGEQGBJDSNSCEDJSSGJDZSGJMNLUJBNLDQUUDQFSUYSQNSUJQNJCGEDCUJDSQJNCZQVZQNSSNTCGWCGEJDSDBNUSUBXJDSQJNSYQJNBGUCGVBGWBGRBDGQMANSLNSYBNJSWJDQJUDQFSUYSQNSDQWASSGQZBMGJNLUZDBBVTQUJSNUBTSJKSGJCSJDZSGJMNLUZDBVQNUDQISUMEESUJSWJDQJUDQFSUYSQNSTQLDQISASSGSTYVBLSWQUQUZDBBVTQUJSNALQVSOQGWSNDBEDJBGBXVQGZQUDCNSQZQJDBVCZVQGWBKGSNKDBGQTSWQZSNJQCGKCVVCQTUDQFSUDQXJSCGDCUKCVVGBSICWSGZSUMAUJQGJCQJSUUMZDUJBNCSUBJDSNJDQGDSQNUQLZBVVSZJSWQXJSNDCUWSQJDDSNSMYBGVSENQGWQNBUSKCJDQENQISQGWUJQJSVLQCNQGWANBMEDJTSJDSASSJVSXNBTQEVQUUZQUSCGKDCZDCJKQUSGZVBUSWCJKQUQASQMJCXMVUZQNQAQSMUQGWQJJDQJJCTSMGFGBKGJBGQJMNQVCUJUBXZBMNUSQENSQJYNCPSCGQUZCSGJCXCZYBCGJBXICSKJDSNSKSNSJKBNBMGWAVQZFUYBJUGSQNBGSSOJNSTCJLBXJDSAQZFQGWQVBGEBGSGSQNJDSBJDSNJDSUZQVSUKSNSSOZSSWCGEVLDQNWQGWEVBUULKCJDQVVJDSQYYSQNQGZSBXAMNGCUDSWEBVWJDSKSCEDJBXJDSCGUSZJKQUISNLNSTQNFQAVSQGWJQFCGEQVVJDCGEUCGJBZBGUCWSNQJCBGCZBMVWDQNWVLAVQTSRMYCJSNXBNDCUBYCGCBGNSUYSZJCGECJ";
char save2[(sizeof(save)/sizeof(save[1]))];

void main(){
int count[26]={0};
char alphabet[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
for (int i = 0; i<(sizeof(save)/sizeof(save[1]))-1;i++){//doin the count
    for(int x = 0; x<(sizeof(alphabet)/sizeof(alphabet[1]))-1;x++){
        if (alphabet[x]==save[i]){
            count[x]++;
        }
    }
}
int highest[3][26]={0};
for(int x = 0; x< 26;x++){//to loop trough each letter
    for (int i = 0; i < 26; i++){//to loop trough each number
        if(highest[0][x]<count[i]){
            highest[0][x] = count[i];
            highest[1][x] = i;
            highest[2][x] = (int)alphabet[i];
        }
    }  
    count[highest[1][x]]=0;
}
for(int i = 0; i < (sizeof(save)/sizeof(save[1]))-1;i++){
    for(int x = 0;x<26;x++){
        if(save[i]==(char)highest[2][x]){
            save2[i]=commency[x];
        }
    }
}
for(int i = 0; i<26;i++){
    printf("%c",(char)highest[2][i]);
}
printf("\n");
printf("%s",save2);
scanf(" ");
}